image: python:3-slim

stages: 
  - test
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .cache/pip

sast: 
  stage: test
include: 
  - template: Security/SAST.gitlab-ci.yml

ansible-lint:
  stage: test
  before_script:
    - pip install ansible ansible-lint
  script:
    - ansible-lint --offline -x 106 roles  

ansible-playbook:
  stage: deploy
  when: manual
  tags: 
    - ansible
  before_script:
    - pip install ansible ansible-lint
    - ansible-galaxy install -r requirements.yml --force
  script: 
    - ansible-playbook -i inventory run.yml --vault-password-file vault.txt --become-password-file become.txt
