---
- name: Make HTTP GET request
  ansible.builtin.uri:
    url: "{{ smartfox_url }}"
    method: GET
    return_content: yes
  register: http_response

- name: Extract xml with regex
  ansible.builtin.set_fact:
    grid_value_raw: "{{ http_response | regex_search('<value id=\"toGridValue\">(.*?)</value>', '\\1') | first }}"
    hid_production_raw: "{{ http_response | regex_search('<value id=\"hidProduction\">(.*?)</value>', '\\1') | first }}"

- name: Convert grid_value and hid_production to float
  ansible.builtin.set_fact:
    grid_value: "{{ grid_value_raw | regex_replace(' kW', '') | regex_replace('\\s', '') | float }}"
    hid_production: "{{ hid_production_raw | regex_replace(' kW', '') | regex_replace('\\s', '') | float }}"

- name: Send notifications via pushover.net
  community.general.pushover:
    title: "Solaranlage - {{ ansible_date_time.iso8601 }}"
    msg: |
      {% if grid_value | float < 0 %}
      Produktion: {{ hid_production }} kW. Es wird ins Netz eingespeist: {{ grid_value }} kW
      {% else %}
      Produktion: {{ hid_production }} kW. Es wird vom Netz bezogen: {{ grid_value }} kW
      {% endif %}
    app_token: "{{ pushover_app_token }}"
    user_key: "{{ pushover_user_key }}"
    pri: 0

- name: Send notifications via pushover.net
  community.general.pushover:
    title: "Solaranlage - Produkte"
    msg: |
      | Produkt | Leistung |
      {% if grid_value | float <= -0.975 %}
      Waschmaschine: 0.975 kW
      {% endif %}
      {% if grid_value | float <= -3.92 %}
      Tumbler: 3.92 kW
      {% endif %}
      {% if grid_value | float <= -2.3 %}
      Backofen: 2.3 kW
      {% endif %}
      {% if grid_value | float <= -0.8 %}
      Steamer: 0.8 kW
      {% endif %}
      {% if grid_value | float <= -0.75 %}
      Geschirrspüler: 0.8 kW
      {% endif %}
      {% if grid_value | float <= -1.4 %}
      Herdplatte (klein): 1.4 kW
      {% endif %}
      {% if grid_value | float <= -2.4 %}
      Herdplatte (gross): 2.4 kW
      {% endif %}
    app_token: "{{ pushover_app_token }}"
    user_key: "{{ pushover_user_key }}"
    pri: 0
  when: grid_value | float <= -0.75