name: Ansible

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "30 7 * * 3"
jobs:
  lint:
      name: Ansible Lint 
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Run ansible-lint
          uses: ansible/ansible-lint@v6
