name: Ansible-Playbook (Products)

on:
  schedule:
    - cron: "*/15 8-18 * * *"
  workflow_dispatch:
    inputs:
      custom_tag_extension:
        description: "Run playbook"
        required: false

jobs:
  lint:
      name: Ansible Playbook 
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - name: Ansible Playbook
          uses: dawidd6/action-ansible-playbook@v2
          with:
            playbook: run.yml
            vault_password: ${{secrets.VAULT}}
            requirements: requirements.yml
            options: |
              -i inventory
              -e "products=true"
